---
apiVersion: v1
kind: Service
metadata:
  name: ops-manager
spec:
  type: NodePort
  selector:
    app: mongodb-enterprise-ops-manager
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb-enterprise-ops-manager
  name: mongodb-enterprise-ops-manager
spec:
  replicas: 1
  serviceName: ops-manager
  selector:
    matchLabels:
      app: mongodb-enterprise-ops-manager
  template:
    metadata:
      labels:
        app: mongodb-enterprise-ops-manager
    spec:
      containers:
      - name: mongodb-enterprise-ops-manager
        image: jmimick/mongodb-enterprise-ops-manager:latest 
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: host
              value: localhost
            port: 8080
            path: /user
          initialDelaySeconds: 90
          timeoutSeconds: 10
        env:
        - name: OM_HOST
          value: mongodb-enterprise-ops-manager-0.ops-manager.mongodb.svc.cluster.local
          #value: ops-manager.mongodb.svc.cluster.local
        volumeMounts:
        - name: mongodb-mms-data
          mountPath: /data
        - name: mongodb-mms-config
          mountPath: /etc/mongodb-mms
        resources:
          requests:
            memory: "4Gi"
  volumeClaimTemplates:
  - metadata:
      name: mongodb-mms-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
  - metadata:
      name: mongodb-mms-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi
