apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-music
  name: spring-music
spec:
  ports:
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-music
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 35.231.78.17
