---
apiVersion: mongodb.com/v1
kind: MongoDbReplicaSet
metadata:
  name: demo-mongodb
  namespace: mongodb
spec:
  members: 5
  version: 4.0.0
  project: mdb-oper-config  
  credentials: mdb-oper-creds
  persistent: true
  podSpec:
    cpu: '0.25'
    memory: 128M
