---
apiVersion: mongodb.com/v1
kind: MongoDbReplicaSet
metadata:
  name: hello-db
  namespace: mongodb
spec:
  members: 3
  version: 4.0.0
  project: hello-mongo-kube  
  credentials: cloud-manager
  persistent: true
  podSpec:
    cpu: '0.25'
    memory: 128M
