---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "mongodb-open-service-broker"
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: "mongodb-open-service-broker"
    spec:
      containers:
      - name: "mongodb-open-service-broker"
        image: "jmimick/mongodb-open-service-broker"
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 5000 
        volumeMounts:
          - mountPath: /broker/broker-config
            name: broker-config
            readOnly: true
      volumes:
      - name: broker-config 
        secret:
          secretName: mongodb-open-service-broker-credentials
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-open-service-broker
  name: mongodb-open-service-broker
spec:
  ports:
  - port: 5000 
    protocol: TCP
    targetPort: 5000 
  selector:
    app: mongodb-open-service-broker 
  type: LoadBalancer
