---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osbmdb  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: osbmdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: osbmdb
    namespace: mongodb
---
apiVersion: v1
kind: Secret
metadata:
  name: "mongodb-open-service-broker-credentials"
stringData:
  username: "admin"
  password: "secret123"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-open-service-broker
  name: mongodb-open-service-broker
spec:
  ports:
  - port: 8000 
    protocol: TCP
    targetPort: 8000 
    name: http-ui
  - port: 5000 
    protocol: TCP
    targetPort: 5000
    name: http 
  selector:
    app: mongodb-open-service-broker 
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "mongodb-open-service-broker"
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: "mongodb-open-service-broker"
    spec:
      serviceAccountName: "osbmdb"
      containers:
      - name: "mongodb-open-service-broker"
        image: "jmimick/mongodb-open-service-broker"
        imagePullPolicy: "Always"
        ports:
        - name: http-ui
          containerPort: 8080 
        - name: http
          containerPort: 5000 
        volumeMounts:
          - mountPath: /broker/broker-config
            name: broker-config
            readOnly: true
      volumes:
      - name: broker-config 
        secret:
          secretName: mongodb-open-service-broker-credentials
