---
apiVersion: v1
kind: Service
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb-enterprise-ops-manager
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb-enterprise-ops-manager
  name: mongodb-enterprise-ops-manager
  namespace: mongodb
spec:
  replicas: 1
  serviceName: ops-manager
  selector:
    matchLabels:
      app: mongodb-enterprise-ops-manager
  template:
    metadata:
      labels:
        app: mongodb-enterprise-ops-manager
    spec:
      securityContext:
        fsGroup: 1000080000
        supplementalGroups: [0, 1000080000]
      containers:
      - name: mongodb-enterprise-ops-manager
        image: quay.io/mongodb/mongodb-enterprise-ops-manager:4.0.0.49984.20180625T1427Z-1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 8080
            path: /
          initialDelaySeconds: 600
          timeoutSeconds: 10
        env:
        - name: OM_HOST
          value: ops-manager.mongodb.svc.cluster.local
        volumeMounts:
        - name: mongodb-mms-data
          mountPath: /data
        - name: mongodb-mms-config
          mountPath: /etc/mongodb-mms
        - name: mongodb-mms-global-admin
          mountPath: /etc/mongodb-mms/global-admin
          readOnly: true
        volumes:
        - name: mongodb-mms-global-admin
          secret:
            secretName: mongodb-open-service-broker-credentials
        resources:
          requests:
            memory: "4Gi"
  volumeClaimTemplates:
  - metadata:
      name: mongodb-mms-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
  - metadata:
      name: mongodb-mms-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi
